#!/bin/bash
set -e
if [ $# -lt 1 ]; then
    echo "Provide a file name please."
    exit 1
fi

convert -size 512x512 -background none -gravity center $1 -resize 512x512 -extent 512x512 "${1%.*}-512.png"
